const STORAGE_KEY='weatherQuestGrade6_v1';
const S={player:'',round:[],i:0,score:0,hearts:3,hinted:false,answered:false,log:[],sound:true};
const $=id=>document.getElementById(id);
const screens=['startScreen','gameScreen','resultScreen'];
function show(id){screens.forEach(x=>$(x).classList.toggle('active',x===id));scrollTo({top:0,behavior:'smooth'})}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function newRoundIds(){return shuffle(QUESTION_BANK).slice(0,10).map(q=>q.id)}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(S))}
function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!x?.round?.length)return false;Object.assign(S,x);return true}catch{return false}}
function currentQ(){return QUESTION_BANK.find(x=>x.id===S.round[S.i])}
function beep(ok){if(!S.sound)return;try{const C=window.AudioContext||window.webkitAudioContext;const c=new C(),o=c.createOscillator(),g=c.createGain();o.type='square';o.frequency.value=ok?660:180;g.gain.value=.03;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.08)}catch{}}
function startNew(){S.player=$('playerName').value.trim()||'氣象冒險者';S.round=newRoundIds();S.i=0;S.score=0;S.hearts=3;S.hinted=false;S.answered=false;S.log=[];save();show('gameScreen');render()}
function render(){const x=currentQ();S.hinted=false;S.answered=false;$('hudPlayer').textContent=S.player;$('hudHearts').textContent='♥'.repeat(S.hearts)+'♡'.repeat(3-S.hearts);$('hudXp').textContent=String(S.score).padStart(3,'0');$('hudProgress').textContent=`${S.i+1} / 10`;$('zoneTag').textContent=x.zone;$('skillTag').textContent=x.skill;$('questionId').textContent=x.id;$('topic').textContent=x.topic+'｜閱讀任務';$('passage').textContent=x.passage;$('question').textContent=x.question;$('hintBox').hidden=true;$('feedbackBox').hidden=true;$('nextBtn').hidden=true;$('hintBtn').disabled=false;$('submitBtn').disabled=false;
const multi=x.type==='multi';$('options').innerHTML=x.options.map((o,i)=>`<label class="option"><input type="${multi?'checkbox':'radio'}" name="answer" value="${i}"><span><b>${String.fromCharCode(65+i)}.</b> ${o}</span></label>`).join('');
$('route').innerHTML=S.round.map((_,i)=>`<div class="route-node ${i<S.i?'done':i===S.i?'current':''}">${i<S.i?'✓':i+1}</div>`).join('');save()}
function selected(){return [...document.querySelectorAll('input[name="answer"]:checked')].map(x=>+x.value)}
function isCorrect(x,a){if(x.type==='multi'){const A=[...x.answer].sort(),B=[...a].sort();return A.length===B.length&&A.every((v,i)=>v===B[i])}return a.length===1&&a[0]===x.answer}
function answerText(x,a){return (Array.isArray(a)?a:[a]).map(i=>String.fromCharCode(65+i)+'. '+x.options[i]).join('；')}
function submit(){if(S.answered)return;const x=currentQ(),a=selected();if(!a.length){$('feedbackBox').hidden=false;$('feedbackBox').className='feedback bad';$('feedbackBox').textContent='⚠ 請先選擇答案。';return}const ok=isCorrect(x,a);S.answered=true;if(ok)S.score+=S.hinted?80:100;else S.hearts=Math.max(0,S.hearts-1);S.log.push({id:x.id,selected:a,correct:ok,answer:x.answer,hinted:S.hinted});$('hudHearts').textContent='♥'.repeat(S.hearts)+'♡'.repeat(3-S.hearts);$('hudXp').textContent=String(S.score).padStart(3,'0');$('feedbackBox').hidden=false;$('feedbackBox').className='feedback '+(ok?'good':'bad');$('feedbackBox').innerHTML=`<b>${ok?'✓ 判讀成功！':'✕ 踩到氣象陷阱！'}</b><br>${ok?'':'正確答案：'+answerText(x,x.answer)+'<br>'}${x.explanation}`;$('submitBtn').disabled=true;$('hintBtn').disabled=true;document.querySelectorAll('input[name="answer"]').forEach(e=>e.disabled=true);$('nextBtn').hidden=false;beep(ok);save()}
function hint(){if(S.hinted||S.answered)return;S.hinted=true;$('hintBox').hidden=false;$('hintBox').innerHTML='<b>提示晶片：</b> '+currentQ().hint+'<br><small>本題答對可得 80 XP</small>';$('hintBtn').disabled=true;save()}
function next(){if(!S.answered)return;if(S.i<9){S.i++;render()}else finish()}
function finish(){const c=S.log.filter(x=>x.correct).length;let title,badge;if(c===10){title='SS級・氣象核心完全解鎖！';badge='🏆'}else if(c>=8){title='S級・氣象分析師！';badge='⭐'}else if(c>=6){title='A級・風雲探險家！';badge='🛰️'}else{title='完成任務，再挑戰一次！';badge='🧭'}$('resultIcon').textContent=badge;$('resultTitle').textContent=title;$('resultStats').innerHTML=`<b>${S.player}</b><br>答對 ${c}/10　｜　正確率 ${c*10}%<br>總 XP：${S.score}　｜　剩餘能量：${S.hearts}/3`;show('resultScreen');save()}
function review(){const box=$('reviewBox');box.hidden=!box.hidden;if(box.hidden)return;box.innerHTML=S.log.map((r,i)=>{const x=QUESTION_BANK.find(q=>q.id===r.id);return `<div class="review-item ${r.correct?'good':'bad'}"><b>#${i+1} ${r.correct?'✓':'✕'} ${x.topic} (${x.id})</b><br>你的答案：${answerText(x,r.selected)}<br>正確答案：${answerText(x,x.answer)}<br>${x.explanation}</div>`}).join('')}
$('startBtn').onclick=startNew;$('submitBtn').onclick=submit;$('hintBtn').onclick=hint;$('nextBtn').onclick=next;$('againBtn').onclick=()=>{show('startScreen');startNew()};$('reviewBtn').onclick=review;$('resetBtn').onclick=()=>{if(confirm('放棄目前進度並重新開始？')){localStorage.removeItem(STORAGE_KEY);location.reload()}};$('soundBtn').onclick=()=>{S.sound=!S.sound;$('soundBtn').textContent=S.sound?'♪ 音效：開':'♪ 音效：關';save()};$('continueBtn').onclick=()=>{show('gameScreen');render()};
const has=load();$('continueBtn').hidden=!has;if(has)$('playerName').value=S.player||'';$('soundBtn').textContent=S.sound?'♪ 音效：開':'♪ 音效：關';